import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

import { parseRule, syncRules } from '../scripts/sync-rules.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SCRIPT = path.join(HERE, '..', 'scripts', 'sync-rules.mjs');
const FIXTURE = path.join(HERE, 'fixtures', 'rules-sync');
const ALL = 'cursor,copilot,cline,windsurf';

const tmpDirs = [];
function project() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sync-rules-test-'));
  tmpDirs.push(dir);
  fs.cpSync(FIXTURE, dir, { recursive: true });
  return dir;
}
process.on('exit', () => {
  for (const dir of tmpDirs) fs.rmSync(dir, { recursive: true, force: true });
});

const read = (dir, rel) => fs.readFileSync(path.join(dir, rel), 'utf8');
const exists = (dir, rel) => fs.existsSync(path.join(dir, rel));
const sync = (dir, targets = ALL, flags = []) => {
  const r = spawnSync(process.execPath, [SCRIPT, '--dir', dir, '--targets', targets, ...flags], { encoding: 'utf8' });
  return { code: r.status, out: r.stdout, err: r.stderr };
};
const marker = (rel) =>
  `<!-- generated by claude-setup from .claude/rules/${rel}; edit the source and re-run sync-rules -->`;

test('parseRule reads paths as a list, a comma string, or not at all', () => {
  assert.deepEqual(parseRule('---\npaths:\n  - "a/**"\n  - b/*.ts # note\n---\nbody').paths, ['a/**', 'b/*.ts']);
  assert.deepEqual(parseRule("---\npaths: 'a/**, src/*.{ts,tsx}'\n---\nx").paths, ['a/**', 'src/*.{ts,tsx}']);
  assert.deepEqual(parseRule('---\npaths: [a/**, "b/**"]\n---\nx').paths, ['a/**', 'b/**']);
  assert.deepEqual(parseRule('# Title\nbody').paths, []);
});

test('parseRule keeps the body exactly and normalizes CRLF', () => {
  const r = parseRule('---\r\npaths: a/**\r\n---\r\n\r\n# T\r\n  indented\r\n\r\n');
  assert.equal(r.body, '\n# T\n  indented\n\n');
  assert.equal(parseRule('no frontmatter\n').body, 'no frontmatter\n');
});

test('cursor output', () => {
  const dir = project();
  assert.equal(sync(dir, 'cursor').code, 0);
  assert.equal(
    read(dir, '.cursor/rules/api.mdc'),
    `---\ndescription: API rules\nglobs: src/api/**/*.ts,src/server/**/*.{ts,tsx}\nalwaysApply: false\n---\n${marker('api.md')}\n\n# API rules\n\n- Validate input at the boundary.\n- Return typed errors.\n`,
  );
  const tests = read(dir, '.cursor/rules/tests.mdc');
  assert.match(tests, /^description: Run the single test file after editing it\.$/m);
  assert.match(tests, /^globs: tests\/\*\*\/\*\.test\.ts,\*\*\/\*\.spec\.ts$/m);
  const general = read(dir, '.cursor/rules/general.mdc');
  assert.match(general, /^alwaysApply: true$/m);
  assert.doesNotMatch(general, /globs:/);
  const db = read(dir, '.cursor/rules/sub-db.mdc');
  assert.match(db, /^description: "Database: migrations"$/m); // colon forces quoting
  assert.match(db, new RegExp(marker('sub/db.md').replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
});

test('copilot output', () => {
  const dir = project();
  assert.equal(sync(dir, 'copilot').code, 0);
  const api = read(dir, '.github/instructions/api.instructions.md');
  assert.ok(api.startsWith('---\napplyTo: "src/api/**/*.ts,src/server/**/*.{ts,tsx}"\n---\n'));
  assert.match(read(dir, '.github/instructions/general.instructions.md'), /^applyTo: "\*\*"$/m);
  assert.ok(exists(dir, '.github/instructions/sub-db.instructions.md'));
});

test('cline output omits frontmatter without paths', () => {
  const dir = project();
  assert.equal(sync(dir, 'cline').code, 0);
  assert.ok(read(dir, '.clinerules/api.md').startsWith('---\npaths:\n  - "src/api/**/*.ts"\n  - "src/server/**/*.{ts,tsx}"\n---\n'));
  assert.equal(read(dir, '.clinerules/general.md'), `${marker('general.md')}\n\n# General conventions\n\n- Small commits.\n`);
});

test('windsurf output', () => {
  const dir = project();
  assert.equal(sync(dir, 'windsurf').code, 0);
  assert.ok(read(dir, '.windsurf/rules/tests.md').startsWith('---\ntrigger: glob\nglobs: tests/**/*.test.ts,**/*.spec.ts\n---\n'));
  assert.ok(read(dir, '.windsurf/rules/general.md').startsWith('---\ntrigger: always_on\n---\n'));
});

test('body bytes are preserved after the marker', () => {
  const dir = project();
  sync(dir, ALL);
  const body = parseRule(read(dir, '.claude/rules/api.md')).body;
  for (const rel of ['.cursor/rules/api.mdc', '.github/instructions/api.instructions.md', '.clinerules/api.md', '.windsurf/rules/api.md']) {
    assert.ok(read(dir, rel).endsWith(`${marker('api.md')}\n\n${body}`), rel);
  }
});

test('second run is idempotent: everything unchanged', () => {
  const dir = project();
  const first = sync(dir);
  assert.equal(first.code, 0);
  assert.match(first.out, /summary: 16 write, 0 unchanged/);
  const second = sync(dir);
  assert.equal(second.code, 0);
  assert.match(second.out, /summary: 0 write, 16 unchanged, 0 remove, 0 conflict/);
  assert.doesNotMatch(second.out, /^write/m);
});

test('--check writes nothing, fails before sync and passes after', () => {
  const dir = project();
  const before = sync(dir, ALL, ['--check']);
  assert.equal(before.code, 1);
  assert.match(before.out, /^write\s+cursor\s+\.cursor\/rules\/api\.mdc$/m);
  assert.equal(exists(dir, '.cursor'), false);
  assert.equal(sync(dir).code, 0);
  assert.equal(sync(dir, ALL, ['--check']).code, 0);
  fs.appendFileSync(path.join(dir, '.claude/rules/general.md'), '- Another rule.\n');
  assert.equal(sync(dir, ALL, ['--check']).code, 1);
});

test('--dry-run prints planned writes and writes nothing', () => {
  const dir = project();
  const r = sync(dir, ALL, ['--dry-run']);
  assert.equal(r.code, 0);
  assert.match(r.out, /^write\s+windsurf\s+\.windsurf\/rules\/sub-db\.md$/m);
  assert.match(r.out, /dry run/);
  for (const d of ['.cursor', '.github', '.clinerules', '.windsurf']) assert.equal(exists(dir, d), false, d);
});

test('a hand-written target file is a conflict and is not overwritten', () => {
  const dir = project();
  fs.mkdirSync(path.join(dir, '.clinerules'));
  fs.writeFileSync(path.join(dir, '.clinerules/api.md'), '# my own rules\n');
  const r = sync(dir, 'cline');
  assert.equal(r.code, 1);
  assert.match(r.out, /^conflict\s+cline\s+\.clinerules\/api\.md/m);
  assert.equal(read(dir, '.clinerules/api.md'), '# my own rules\n');
  assert.ok(exists(dir, '.clinerules/tests.md')); // the other rules still sync
  assert.equal(sync(dir, 'cline', ['--check']).code, 1);
});

test('stale generated files are removed; hand-written ones are kept', () => {
  const dir = project();
  sync(dir);
  fs.rmSync(path.join(dir, '.claude/rules/tests.md'));
  fs.writeFileSync(path.join(dir, '.cursor/rules/mine.mdc'), '---\nalwaysApply: true\n---\nhand written\n');

  const dry = sync(dir, ALL, ['--dry-run']);
  assert.equal(dry.code, 0);
  assert.match(dry.out, /^remove\s+cursor\s+\.cursor\/rules\/tests\.mdc$/m);
  assert.ok(exists(dir, '.cursor/rules/tests.mdc'));
  assert.equal(sync(dir, ALL, ['--check']).code, 1);

  const real = sync(dir);
  assert.equal(real.code, 0);
  assert.match(real.out, /summary: 0 write, 12 unchanged, 4 remove, 0 conflict/);
  for (const rel of ['.cursor/rules/tests.mdc', '.github/instructions/tests.instructions.md', '.clinerules/tests.md', '.windsurf/rules/tests.md']) {
    assert.equal(exists(dir, rel), false, rel);
  }
  assert.ok(exists(dir, '.cursor/rules/mine.mdc'));
});

test('editing a source updates the generated file', () => {
  const dir = project();
  sync(dir);
  fs.appendFileSync(path.join(dir, '.claude/rules/api.md'), '- New rule.\n');
  const r = sync(dir);
  assert.match(r.out, /summary: 4 write, 12 unchanged/);
  assert.match(read(dir, '.clinerules/api.md'), /- New rule\.\n$/);
});

test('usage errors exit 2', () => {
  const dir = project();
  const none = spawnSync(process.execPath, [SCRIPT, '--dir', dir], { encoding: 'utf8' });
  assert.equal(none.status, 2);
  assert.match(none.stderr, /usage:/);
  const bad = sync(dir, 'cursor,vim');
  assert.equal(bad.code, 2);
  assert.match(bad.err, /unknown target: vim/);
  assert.equal(spawnSync(process.execPath, [SCRIPT, '--bogus', '--targets', 'cursor'], { encoding: 'utf8' }).status, 2);
});

test('default --dir is the current directory', () => {
  const dir = project();
  const r = spawnSync(process.execPath, [SCRIPT, '--targets', 'cline'], { cwd: dir, encoding: 'utf8' });
  assert.equal(r.status, 0);
  assert.ok(exists(dir, '.clinerules/api.md'));
});

test('works through a symlinked invocation and importing does not run the CLI', () => {
  const dir = project();
  const link = path.join(dir, 'sync-link.mjs');
  fs.symlinkSync(SCRIPT, link);
  const r = spawnSync(process.execPath, [link, '--dir', dir, '--targets', 'cline'], { encoding: 'utf8' });
  assert.equal(r.status, 0);
  assert.match(r.stdout, /summary: 4 write/);
  // The import at the top of this file already proved importing prints nothing and exits normally.
  assert.equal(syncRules({ dir, targets: ['cline'], check: true }).changes, 0);
});

test('a project without .claude/rules is a clean no-op', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sync-rules-empty-'));
  tmpDirs.push(dir);
  const r = sync(dir);
  assert.equal(r.code, 0);
  assert.match(r.out, /summary: 0 write, 0 unchanged, 0 remove, 0 conflict/);
});
