#!/usr/bin/env node
// Mirror path-scoped rules from .claude/rules/*.md into other agents' formats.
//
//   node scripts/sync-rules.mjs [--dir <project>] --targets cursor,copilot,cline,windsurf
//                               [--check] [--dry-run]
//
// .claude/rules is the single source. Every generated file carries a marker, so a
// re-run can update it, and a hand-written file at the same path is never touched.
// Exit codes: 0 ok, 1 conflict or (with --check) pending changes, 2 usage error.
// Zero dependencies. Format notes live in research/agents-landscape.md (3.3, 3.4, 3.6, 3.7).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const RULES_DIR = '.claude/rules';
const MARKER_RE = /^<!-- generated by claude-setup from .+ -->$/m;
const markerFor = (rel) =>
  `<!-- generated by claude-setup from ${RULES_DIR}/${rel}; edit the source and re-run sync-rules -->`;

const USAGE = `usage: node sync-rules.mjs [--dir <project>] --targets <list> [--check] [--dry-run]
targets: cursor, copilot, cline, windsurf (comma separated)
  --check     write nothing; exit 1 if any target would change
  --dry-run   print planned actions, write nothing
`;

// ---------------------------------------------------------------------------
// Parsing: only the frontmatter subset we need (`paths:` as list or string)
// ---------------------------------------------------------------------------

function unquote(s) {
  const t = s.trim();
  if (t.length >= 2 && (t[0] === '"' || t[0] === "'") && t[t.length - 1] === t[0]) return t.slice(1, -1);
  return t;
}

// Split on commas that sit outside quotes, brackets and braces ("*.{ts,tsx}" stays whole).
function splitTop(s) {
  const parts = [];
  let depth = 0;
  let quote = null;
  let start = 0;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (quote) {
      if (c === quote) quote = null;
    } else if (c === '"' || c === "'") quote = c;
    else if (c === '{' || c === '[') depth++;
    else if (c === '}' || c === ']') depth--;
    else if (c === ',' && depth === 0) {
      parts.push(s.slice(start, i));
      start = i + 1;
    }
  }
  parts.push(s.slice(start));
  return parts.map((p) => p.trim()).filter(Boolean);
}

// Drop a trailing " # comment" that is outside quotes.
function stripComment(s) {
  let quote = null;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (quote) {
      if (c === quote) quote = null;
    } else if (c === '"' || c === "'") quote = c;
    else if (c === '#' && (i === 0 || /\s/.test(s[i - 1]))) return s.slice(0, i);
  }
  return s;
}

function parsePaths(fmLines) {
  const at = fmLines.findIndex((l) => /^paths\s*:/.test(l));
  if (at < 0) return [];
  const rest = stripComment(fmLines[at].replace(/^paths\s*:/, '')).trim();
  if (rest.startsWith('[')) {
    return splitTop(rest.slice(1, rest.lastIndexOf(']'))).map(unquote).filter(Boolean);
  }
  if (rest) return splitTop(rest).map(unquote).flatMap(splitTop);
  const items = [];
  for (const line of fmLines.slice(at + 1)) {
    const text = stripComment(line);
    if (!text.trim()) continue;
    const m = text.match(/^\s*-\s+(.+)$/);
    if (m) items.push(unquote(m[1]));
    else if (!/^\s/.test(text)) break;
  }
  return items.filter(Boolean);
}

// -> { paths: string[], body: string }. Line endings are normalized to \n; the body is untouched.
export function parseRule(raw) {
  const text = raw.replace(/^﻿/, '').replace(/\r\n/g, '\n');
  const m = text.match(/^---[ \t]*\n([\s\S]*?\n)?(?:---|\.\.\.)[ \t]*(?:\n|$)/);
  if (!m) return { paths: [], body: text };
  return { paths: parsePaths((m[1] || '').split('\n')), body: text.slice(m[0].length) };
}

// ---------------------------------------------------------------------------
// Rendering, one function per target
// ---------------------------------------------------------------------------

// First markdown heading, else first non-empty line, else the rule name.
function describe(body, name) {
  const lines = body.split('\n').map((l) => l.trim()).filter(Boolean);
  const heading = lines.find((l) => /^#{1,6}\s+\S/.test(l));
  const text = heading ? heading.replace(/^#{1,6}\s+/, '').replace(/\s+#+$/, '') : lines[0];
  return text || name;
}

// Plain YAML scalar when safe, double-quoted otherwise.
const scalar = (s) => (/^[\w][^:#]*$/.test(s) && !/\s$/.test(s) ? s : JSON.stringify(s));

const quoted = (s) => JSON.stringify(s);
const withFrontmatter = (lines, rule, name) =>
  `---\n${lines.join('\n')}\n---\n${markerFor(`${name}.md`)}\n\n${rule.body}`;

// Cursor: description / globs / alwaysApply. Globs are comma-joined and unquoted, as in
// Cursor's documented example (research 3.3, from search summaries; not verified on cursor.com).
function renderCursor(rule, rel) {
  const lines = [`description: ${scalar(describe(rule.body, rel))}`];
  if (rule.paths.length) lines.push(`globs: ${rule.paths.join(',')}`);
  lines.push(`alwaysApply: ${rule.paths.length === 0}`);
  return withFrontmatter(lines, rule, rel);
}

// Copilot: `applyTo` is one quoted string of comma-separated globs (research 3.4, from github/docs).
function renderCopilot(rule, rel) {
  return withFrontmatter([`applyTo: ${quoted(rule.paths.length ? rule.paths.join(',') : '**')}`], rule, rel);
}

// Cline: `paths:` list; no frontmatter means always active (research 3.7, from cline/cline docs).
function renderCline(rule, rel) {
  if (!rule.paths.length) return `${markerFor(`${rel}.md`)}\n\n${rule.body}`;
  return withFrontmatter(['paths:', ...rule.paths.map((p) => `  - ${quoted(p)}`)], rule, rel);
}

// Windsurf: trigger glob|always_on plus globs. Less certain: the docs were only seen through
// search summaries (research 3.6), so globs are comma-joined and unquoted like the one example.
function renderWindsurf(rule, rel) {
  const lines = rule.paths.length ? ['trigger: glob', `globs: ${rule.paths.join(',')}`] : ['trigger: always_on'];
  return withFrontmatter(lines, rule, rel);
}

export const TARGETS = {
  cursor: { dir: '.cursor/rules', ext: '.mdc', render: renderCursor },
  copilot: { dir: '.github/instructions', ext: '.instructions.md', render: renderCopilot },
  cline: { dir: '.clinerules', ext: '.md', render: renderCline },
  windsurf: { dir: '.windsurf/rules', ext: '.md', render: renderWindsurf },
};

// ---------------------------------------------------------------------------
// Sync
// ---------------------------------------------------------------------------

// Source rules as { rel: "sub/x.md", name: "sub-x" }, sorted. Symlinked directories are skipped.
function listRules(root) {
  const base = path.join(root, RULES_DIR);
  const found = [];
  const walk = (relDir) => {
    let entries;
    try {
      entries = fs.readdirSync(path.join(base, relDir), { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries.sort((a, b) => (a.name < b.name ? -1 : 1))) {
      const rel = relDir ? `${relDir}/${e.name}` : e.name;
      if (e.isDirectory()) walk(rel);
      else if (e.name.endsWith('.md') && (e.isFile() || e.isSymbolicLink())) found.push(rel);
    }
  };
  walk('');
  return found.map((rel) => ({ rel, name: rel.slice(0, -3).replace(/\//g, '-') }));
}

function readIfExists(file) {
  try {
    return fs.readFileSync(file, 'utf8');
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
}

// Generated files (marker present) in a target dir whose source rule no longer exists.
function staleFiles(dir, ext, keep) {
  let names;
  try {
    names = fs.readdirSync(dir);
  } catch {
    return [];
  }
  return names
    .filter((n) => n.endsWith(ext) && !keep.has(n))
    .filter((n) => MARKER_RE.test(readIfExists(path.join(dir, n)) || ''))
    .sort();
}

// Returns { actions: [{ action, target, file }], conflicts, changes }.
export function syncRules({ dir = process.cwd(), targets, check = false, dryRun = false }) {
  const root = path.resolve(dir);
  const readOnly = check || dryRun;
  const actions = [];
  const record = (action, target, file) => actions.push({ action, target, file });
  const rules = listRules(root);

  for (const target of targets) {
    const { dir: outDir, ext, render } = TARGETS[target];
    const keep = new Set();
    const seen = new Set();
    for (const { rel, name } of rules) {
      const file = `${outDir}/${name}${ext}`;
      if (seen.has(name)) {
        record('conflict', target, `${file} (name clash: ${rel} maps to an earlier rule)`);
        continue;
      }
      seen.add(name);
      keep.add(`${name}${ext}`);
      const rule = parseRule(fs.readFileSync(path.join(root, RULES_DIR, rel), 'utf8'));
      const output = render(rule, rel.slice(0, -3), name);
      const abs = path.join(root, file);
      const current = readIfExists(abs);
      if (current === null || MARKER_RE.test(current)) {
        if (current === output) {
          record('unchanged', target, file);
        } else {
          record('write', target, file);
          if (!readOnly) {
            fs.mkdirSync(path.dirname(abs), { recursive: true });
            fs.writeFileSync(abs, output);
          }
        }
      } else {
        record('conflict', target, `${file} (exists without the generated marker; left alone)`);
      }
    }
    for (const n of staleFiles(path.join(root, outDir), ext, keep)) {
      record('remove', target, `${outDir}/${n}`);
      if (!readOnly) fs.rmSync(path.join(root, outDir, n));
    }
  }

  const count = (a) => actions.filter((x) => x.action === a).length;
  return { root, actions, conflicts: count('conflict'), changes: count('write') + count('remove') };
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(argv) {
  const opts = { dir: process.cwd(), targets: [], check: false, dryRun: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') opts.check = true;
    else if (a === '--dry-run') opts.dryRun = true;
    else if (a === '--dir' || a === '--targets') {
      const v = argv[++i];
      if (v === undefined) return { error: `${a} needs a value` };
      if (a === '--dir') opts.dir = v;
      else opts.targets = v.split(',').map((t) => t.trim()).filter(Boolean);
    } else if (a.startsWith('--dir=')) opts.dir = a.slice(6);
    else if (a.startsWith('--targets=')) opts.targets = a.slice(10).split(',').map((t) => t.trim()).filter(Boolean);
    else if (a === '-h' || a === '--help') return { help: true };
    else return { error: `unknown argument: ${a}` };
  }
  if (!opts.targets.length) return { error: 'missing --targets' };
  const unknown = opts.targets.filter((t) => !TARGETS[t]);
  if (unknown.length) return { error: `unknown target: ${unknown.join(', ')}` };
  opts.targets = [...new Set(opts.targets)];
  return { opts };
}

// Returns the exit code.
export function run(argv, out = process.stdout, err = process.stderr) {
  const parsed = parseArgs(argv);
  if (parsed.help) {
    out.write(USAGE);
    return 0;
  }
  if (parsed.error) {
    err.write(`sync-rules: ${parsed.error}\n${USAGE}`);
    return 2;
  }
  const { opts } = parsed;
  if (!fs.existsSync(opts.dir) || !fs.statSync(opts.dir).isDirectory()) {
    err.write(`sync-rules: not a directory: ${opts.dir}\n`);
    return 2;
  }
  const result = syncRules(opts);
  for (const { action, target, file } of result.actions) out.write(`${action.padEnd(9)} ${target.padEnd(8)} ${file}\n`);
  const n = (a) => result.actions.filter((x) => x.action === a).length;
  const mode = opts.check ? ' (check: nothing written)' : opts.dryRun ? ' (dry run: nothing written)' : '';
  out.write(`summary: ${n('write')} write, ${n('unchanged')} unchanged, ${n('remove')} remove, ${n('conflict')} conflict${mode}\n`);
  if (result.conflicts) return 1;
  if (opts.check && result.changes) return 1;
  return 0;
}

// True when this file is the process entry point, including via a symlinked path.
function isEntryPoint() {
  if (!process.argv[1]) return false;
  try {
    return fs.realpathSync(process.argv[1]) === fs.realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
}

if (isEntryPoint()) {
  try {
    process.exitCode = run(process.argv.slice(2));
  } catch (e) {
    process.stderr.write(`sync-rules: ${e && e.message ? e.message : e}\n`);
    process.exitCode = 1;
  }
}
